[package]
name = "async_test"
version = "0.1.0"
authors = ["byshnev"]

[dependencies]
tokio = "0.1.3"
mio = "0.6.14"
tokio-core = "0.1"
tokio-io = "0.1"
futures = "0.1.18"
bytes = "0.4.2"
nonblock = "0.1.0"
